name: climate-analysis

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyter
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn

  - xarray
  - dask
  - bottleneck
  - numba

  - netcdf4
  - h5netcdf
  - cftime

  - cartopy
  - pyproj
  - shapely

  - cmocean
  - metpy
  - cf_xarray
  - xesmf

